version: '2'
services:
  web:
    image: auction_web
    container_name: auction_web
    environment:
      NODE_ENV: production
    ports:
     - "8080:8080"
    volumes:
     - .:/auction
    depends_on:
      - db
  db:
    image: elmauro/postgresql
    container_name: auction_db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
volumes:
  db-volume: